name: autoshopsapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  device_preview: ^1.2.0
  syncfusion_flutter_gauges: ^24.2.6

  flutter_blue_plus: ^1.3.2
  http: ^0.13.6 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
